### ISSUE TITLE
produce_async_batched

### ISSUE THREAD

**Issue by gaynetdinov** [helpshift/ekaf#16]
Hello.

I'm a bit confused with the documentation regarding the way how to produce messages async and in batches. 

The `README` says the following
```
%% sync
{buffered, _Partition, _BufferSize} =
    ekaf:produce_async_batched(
        Topic,
        [ekaf_utils:itob(X) || X<- lists:seq(1,1000) ]
    ).

%% async
{buffered, _Partition, _BufferIndex} =
    ekaf:produce_async_batched(
        Topic,
        [<<"foo">>, {<<"key">>, <<"value">>}, <<"back_to_binary">> ]
    ).
```

It's a bit weird to me that both sync and async ways to send messages in batches are done using the same method `produce_async_batched`. Is that expected to be so or it is a typo? 

Also in this example to send messages asynchronous in batches I don't quite get the values which are used. What is `<<"foo">>`? As I understand `<<"key">>` is routing key for the message which is represented as `<<"value">>` here, right? What is `<<"back_to_binary">>`? Also if I open `ekaf_tests.erl` I see that `produce_async_batched` is called as the following:
```
Sent = [ <<(ekaf_utils:itob(X))/binary,".async multi batch">> || X<- lists:seq(9,19)],
Response  = ekaf:produce_async_batched(?TEST_TOPIC, Sent ),
```
or
```
Sent = <<"20.async in batch">>,
Response  = ekaf:produce_async_batched(?TEST_TOPIC, Sent),
```

As I can see in the examples from the test file there are no `<<"foo">>`, `<<"key">>`, `<<"value">>` or `<<"back_to_binary">>`, there are just topic name and message(or list of messages), that's it. 
Could you please clarify how should I send messages asynchronous in batches? 

Thank you so much!

**Comment by bosky101** [comment]
Yes that is a typo, thanks for bringing it to my attention.

    ekaf:produce_async_batched(
        Topic,
        [<<"foo">>, {<<"key">>, <<"value">>}, <<"back_to_binary">> ]
    )

is a batch of 3 messages. first one is `foo`, second one is `value`, and third being `back_to_binary`

The protocol says it is upto the client to come up to decide which partition.  ekaf does not have a way to provide a PartionPickingFunction ( semanting partitioning as in the docs). Currently this is done via strategies - sticky_round_robin, strict_round_robin, or random.

i recommend using `strict_round_robin` so that load is split nicely between all your brokers and partitions for the topic.

    {ekaf, [
          {ekaf_partition_strategy, strict_round_random}
    ]}

or for different for different topics

    {ekaf, [
        {ekaf_partition_strategy, [
         {<<"heavy_job">>, strict_round_robin},
         {<<"other_event">>, sticky_round_robin},
         {ekaf_partition_strategy,  random}      %% default
     ]}

or dynamically in your code.

    application:load(ekaf),.... % see ekaf_tests.erl for required apps
    application:set_env(ekaf, ekaf_partition_strategy, strict_round_robin),


let me know if this solves your queries.

~B

**Comment by gaynetdinov** [comment]
Thank you for such a great answer!
