### ISSUE TITLE
Can "kafka.bootstrap.server" be changed at runtime?

### ISSUE THREAD

**Issue by dennis-qian** [helpshift/ekaf#45]
Can the parameter be changed after ekaf has started to make it speak to a different Kafka instance?

In addition, what other env params can be changed at runtime and take effect right away?

**Comment by bosky101** [comment]
No. At least right now, the hostname is cached - but performs dns lookups every time.

It's exactly for this reason that I recommend you create `mycluster.kafka.tld` - so that an ops person can switch kafka clusters or add servers etc - without changing/restarting the kafka producers.

btw, it will suffice if the bootstrap server can connect to any one of the kafka brokers. they can each return with the same metadata.

If none of the above are satisfactory - you can submit a  patch that reads back `application:get_env` of the broker rather than from the cached record.

closing for now - but happy to continue the conversation.
~B
